"""Every Dash component id lives here so pages never collide."""

URL = "url"
PAGE = "page"
NOTIFY = "notify"
DOWNLOAD = "download"
NAV_VERSION = "nav-version"

# browse
BROWSE_TYPE = "browse-type"
BROWSE_TEXT = "browse-text"
BROWSE_STATUS = "browse-status"
BROWSE_GRID = "browse-grid"
BROWSE_COUNT = "browse-count"
NEW_OPEN = "new-open"
NEW_MODAL = "new-modal"
NEW_TYPE = "new-type"
NEW_NAME = "new-name"
NEW_DESC = "new-desc"
NEW_SAVE = "new-save"
NEW_FEEDBACK = "new-feedback"

# element
EL_ID = "el-id"
EL_VERSION = "el-version"
EL_TABS = "el-tabs"
EL_NAME = "el-name"
EL_KEY = "el-key"
EL_STATUS = "el-status"
EL_LIFECYCLE = "el-lifecycle"
EL_DESC = "el-desc"
EL_LINKS = "el-links"
EL_SAVE = "el-save"
EL_SAVE_FEEDBACK = "el-save-feedback"
EL_ATTR = "el-attr"  # pattern-matching: {"type": EL_ATTR, "name": <attr>}
EL_REL_DIRECTION = "el-rel-direction"
EL_REL_OTHER = "el-rel-other"
EL_REL_TYPE = "el-rel-type"
EL_REL_QUALIFIER = "el-rel-qualifier"
EL_REL_ADD = "el-rel-add"
EL_REL_FEEDBACK = "el-rel-feedback"
EL_REL_TABLES = "el-rel-tables"
EL_REL_DELETE = "el-rel-delete"  # pattern-matching: {"type": EL_REL_DELETE, "id": <relationship_id>}
EL_GRAPH = "el-graph"
EL_GRAPH_DEPTH = "el-graph-depth"
EL_GRAPH_TAP = "el-graph-tap"
EL_HISTORY = "el-history"

# metamodel
MM_GRAPH = "mm-graph"
MM_DETAIL = "mm-detail"
MM_TYPES_GRID = "mm-types-grid"
MM_RELS_GRID = "mm-rels-grid"
MM_ATTRS_GRID = "mm-attrs-grid"
MM_ADD_TYPE = "mm-add-type"
MM_ADD_REL = "mm-add-rel"
MM_ADD_ATTR = "mm-add-attr"
MM_SAVE = "mm-save"
MM_EXPORT = "mm-export"
MM_RELOAD = "mm-reload"
MM_FEEDBACK = "mm-feedback"
MM_DOMAIN_FILTER = "mm-domain-filter"
MM_LAYOUT = "mm-layout"
MM_NOTATION_DOMAINS_GRID = "mm-notation-domains-grid"
MM_NOTATION_TYPES_GRID = "mm-notation-types-grid"
MM_NOTATION_PREVIEW = "mm-notation-preview"

# impact
IMP_ELEMENT = "imp-element"
IMP_DEPTH = "imp-depth"
IMP_RUN = "imp-run"
IMP_RESULT = "imp-result"
IMP_GRAPH = "imp-graph"

# import
IM_UPLOAD = "im-upload"
IM_FILES = "im-files"
IM_STORE = "im-store"
IM_SOURCE = "im-source"
IM_MAPPING = "im-mapping"
IM_VALIDATE = "im-validate"
IM_LOAD = "im-load"
IM_REPORT = "im-report"

# ask
ASK_INPUT = "ask-input"
ASK_BUTTON = "ask-button"
ASK_RESET = "ask-reset"
ASK_ANSWER = "ask-answer"
ASK_TRACE = "ask-trace"
ASK_PROVIDER = "ask-provider"
ASK_HISTORY = "ask-history"

# Generated architecture views (initiative 2)
MERMAID_SRC = "mermaid-src"  # pattern type: {"type": MERMAID_SRC, "id": <block>}
MERMAID_SVG = "mermaid-svg"
MERMAID_POS = "mermaid-pos"  # shape positions reported by the browser, never saved
MERMAID_RESET = "mermaid-reset"
EL_VIEW_MD = "el-view-md"
EL_VIEW_DRAWIO = "el-view-drawio"
IMP_VIEW_MD = "imp-view-md"
IMP_VIEW_DRAWIO = "imp-view-drawio"
ASK_DOC_MD = "ask-doc-md"
ASK_DOC_DRAWIO = "ask-doc-drawio"
ASK_DOC_STORE = "ask-doc-store"
